version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
    - 1.0.125
  - dependency-name: serde_json
    versions:
    - 1.0.62
    - 1.0.63
    - 1.0.64
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: leptess
    versions:
    - 0.10.0
    - 0.11.0
  - dependency-name: rocket
    versions:
    - 0.4.7
  - dependency-name: rocket_contrib
    versions:
    - 0.4.7
  - dependency-name: sha2
    versions:
    - 0.9.3
  - dependency-name: log
    versions:
    - 0.4.14
  - dependency-name: rust-embed
    versions:
    - 5.9.0
