# docker-compose.yml
version: "3.8"
services:
  shreddr:
    build:
      context: .
      dockerfile: ./docker/alpine/Dockerfile
    image: shreddr:alpine
    environment:
      # Comma separated list of ISO-639 language values e.g.: eng,deu
      - TESS_LANGUAGES=deu,eng
    ports:
      - "8000:8000"
    volumes:
      # Directory where all permanent data is stored
      - ~/tmp/docker/data:/data
      # Input directory from which documents are (non-destructively) imported from
      - ~/tmp/docker/consume:/consume
      # Config file 
      - ~/tmp/docker/shreddr.yml:/shreddr.yml